name: "GreetContributor"
on:
  schedule:
    - cron: "0 1 * * *"
  pull_request:
    types: [opened,synchronize]
    
jobs:
  GreetCommitter:    
    runs-on: ubuntu-latest
    steps:
    - name: "Greet contributor"
      uses: ibakshay/greet-contributors-action@test-release
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
