name: "GreetContributor"
on: workflow_dispatch
    pull_request:
      types: [opened,synchronize]
    
jobs:
  GreetCommitter:    
    runs-on: ubuntu-latest
    steps:
    - name: "Greet contributor"
      uses: ibakshay/greet-contributors-action@test-release
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
